site_title: InnoCellence

#source: source
#destination: dist
port: 8888

#Google Analytics ID, auto populated to all pages
#google_analytics: xxxxxxxxxx


#Facebook Sharing
#facebook_app_id: xxxxxxxx

#URL Prefixing
siteurl:
baseurl:

#Permalinks
permalink: /:categories/:year/:month/:day/:slug/

#Set Syntax Highlighter
#highlighter: rouge

#encoding
encoding: UTF-8

#sass import directory
sass:
  sass_dir: assets/_scss
  style: compressed

#Plugins
plugins:  
  - jekyll-redirect-from

#Collections
collections:
  jobs: 
    output: false
  whitepaper: 
    output: true
  news: 
    output: true
  
#Default Front Matter
defaults:
  -
    scope: 
      path: ''
      type: 'pages'
    values:
      lang: en
  
  -
    scope:
      path: 'cn'
    values:
      lang: zh
      
  -
    scope:
      path: 'jp'
    values:
      lang: jp   
      
  -
    scope:
      path: ''
      type: 'jobs'
    values:
      lang: en
      
  -
    scope:
      path: ''
      type: 'whitepaper'
    values:
      lang: en    
      layout: 'post'
  
  -
    scope:
      path: ''
      type: 'news'
    values:
      lang: en    
      layout: 'post'