#####################
###### English ######
#####################
en:
  title       : InnoCellence
  byline      : Excellence in Digital Innovation
  keywords    : 
  author      : InnoCellence Singapore Pte. Ltd.

#####################
###### Chinese ######
#####################
zh:
  title       : InnoCellence
  byline      : 致力于卓越的数字化创新
  keywords    : 
  author      : InnoCellence Dalian
  
  
######################
###### Japanese ######
######################
jp:
  title       : InnoCellence
  byline      : Excellence in Digital Innovation
  keywords    : 
  author      : InnoCellence Japan K.K.