#####################
###### English ######
#####################
en:
  - text: Innovation Consulting
    img:  icon_innovation.svg
    url:  innovation-consulting
  - text: Design & UX
    img:  icon_design.svg
    url:  design-ux
  - text: Application Development
    img:  icon_development.svg
    url:  application-development
  - text: Rapid Prototyping
    img:  icon_prototype.svg
    url: 
  - text: Digital Services
    img:  icon_digital.svg  
    url: 
  - text: Data Analytics
    img:  icon_analytics.svg
    url:

#####################
###### Chinese ######
#####################
zh:
  - text: 创新顾问
    img:  icon_brain.svg
  - text: 设计与用户体验
    img:  icon_pen.svg
  - text: 技术决绝方案
    img:  icon_gear.svg
  - text: 数据分析
    img:  icon_chart.svg
  - text: 数字服务
    img:  icon_content.svg
  
  
######################
###### Japanese ######
######################
jp:
  - text:
    img: 
  - text: 
    img: 